import { useMemo, useState } from 'react';
import Layout from '../components/Layout';
import Modal from '../components/Modal';

const initialCustomers=[
 {id:1,name:'Ravi Kumar',phone:'9876543210',due:8000,status:'Pending'},
 {id:2,name:'Sita Devi',phone:'9876501234',due:15000,status:'Overdue'},
 {id:3,name:'Arjun',phone:'9123456780',due:0,status:'Paid'}
];
const initialProducts=[{id:1,name:'Laptop',brand:'Dell',qty:5,price:50000},{id:2,name:'Mouse',brand:'HP',qty:20,price:800}];
const initialExpenses=[{id:1,date:'18 Sep',description:'Product purchase',category:'Purchase',amount:10000},{id:2,date:'17 Sep',description:'Transport',category:'Travel',amount:2000}];

export default function Management({onLogout}){
 const [tab,setTab]=useState('customers'); const [customers,setCustomers]=useState(initialCustomers); const [products,setProducts]=useState(initialProducts); const [expenses,setExpenses]=useState(initialExpenses); const [modal,setModal]=useState(null); const [search,setSearch]=useState('');
 const filtered=useMemo(()=>customers.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())||c.phone.includes(search)),[customers,search]);
 const addCustomer=e=>{e.preventDefault();const f=new FormData(e.target);setCustomers([...customers,{id:Date.now(),name:f.get('name'),phone:f.get('phone'),due:Number(f.get('due')),status:'Pending'}]);setModal(null);};
 const addProduct=e=>{e.preventDefault();const f=new FormData(e.target);setProducts([...products,{id:Date.now(),name:f.get('name'),brand:f.get('brand'),qty:Number(f.get('qty')),price:Number(f.get('price'))}]);setModal(null);};
 const addExpense=e=>{e.preventDefault();const f=new FormData(e.target);setExpenses([...expenses,{id:Date.now(),date:f.get('date'),description:f.get('description'),category:f.get('category'),amount:Number(f.get('amount'))}]);setModal(null);};
 return <Layout onLogout={onLogout}><section className="page-heading"><div><p className="eyebrow">MANAGEMENT</p><h1>Business Management</h1><p className="muted">Manage customers, payments, products and expenses in one place.</p></div></section>
 <div className="tabs">{['customers','payments','products','expenses'].map(t=><button key={t} className={tab===t?'tab active':'tab'} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 <section className="panel table-panel">
 {tab==='customers' && <><div className="panel-title"><div><h2>Customers</h2><p className="muted">Track customer balances and reminders.</p></div><button className="primary-btn" onClick={()=>setModal('customer')}>+ Add Customer</button></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer..."/><Table headers={['Name','Phone','Due','Status','Actions']} rows={filtered.map(c=>[<strong>{c.name}</strong>,c.phone,`₹${c.due.toLocaleString('en-IN')}`,<span className={`status ${c.status.toLowerCase()}`}>{c.status}</span>,<div className="row-actions"><a href={`tel:${c.phone}`}>📞</a><button onClick={()=>alert(`Reminder for ${c.name}`)}>🔔</button></div>])}/></>}
 {tab==='payments' && <><div className="panel-title"><div><h2>Payments</h2><p className="muted">Pending, overdue and paid customer payments.</p></div></div><Table headers={['Customer','Amount','Due','Status','Action']} rows={customers.map(c=>[c.name,`₹${c.due.toLocaleString('en-IN')}`,c.status==='Overdue'?'Overdue':'Today',<span className={`status ${c.status.toLowerCase()}`}>{c.status}</span>,c.due>0?<button className="secondary-btn small" onClick={()=>alert(`Reminder for ${c.name}`)}>Remind</button>:'—'])}/></>}
 {tab==='products' && <><div className="panel-title"><div><h2>Products</h2><p className="muted">Keep a simple product list.</p></div><button className="primary-btn" onClick={()=>setModal('product')}>+ Add Product</button></div><Table headers={['Product','Brand','Quantity','Price','Action']} rows={products.map(p=>[p.name,p.brand,p.qty,`₹${p.price.toLocaleString('en-IN')}`,<button className="text-btn" onClick={()=>setProducts(products.filter(x=>x.id!==p.id))}>Delete</button>])}/></>}
 {tab==='expenses' && <><div className="panel-title"><div><h2>Expenses</h2><p className="muted">Record essential business expenses.</p></div><button className="primary-btn" onClick={()=>setModal('expense')}>+ Add Expense</button></div><div className="expense-total">Total Expenses: <strong>₹{expenses.reduce((a,b)=>a+b.amount,0).toLocaleString('en-IN')}</strong></div><Table headers={['Date','Description','Category','Amount','Action']} rows={expenses.map(x=>[x.date,x.description,x.category,`₹${x.amount.toLocaleString('en-IN')}`,<button className="text-btn" onClick={()=>setExpenses(expenses.filter(e=>e.id!==x.id))}>Delete</button>])}/></>}
 </section>
 {modal==='customer'&&<Modal title="Add Customer" onClose={()=>setModal(null)}><form className="modal-form" onSubmit={addCustomer}><label>Name<input name="name" required/></label><label>Phone<input name="phone" required/></label><label>Amount Due<input name="due" type="number" min="0" required/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setModal(null)}>Cancel</button><button className="primary-btn">Save Customer</button></div></form></Modal>}
 {modal==='product'&&<Modal title="Add Product" onClose={()=>setModal(null)}><form className="modal-form" onSubmit={addProduct}><label>Product<input name="name" required/></label><label>Brand<input name="brand" required/></label><label>Quantity<input name="qty" type="number" min="0" required/></label><label>Price<input name="price" type="number" min="0" required/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setModal(null)}>Cancel</button><button className="primary-btn">Save Product</button></div></form></Modal>}
 {modal==='expense'&&<Modal title="Add Expense" onClose={()=>setModal(null)}><form className="modal-form" onSubmit={addExpense}><label>Date<input name="date" placeholder="20 Sep" required/></label><label>Description<input name="description" required/></label><label>Category<input name="category" required/></label><label>Amount<input name="amount" type="number" min="0" required/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setModal(null)}>Cancel</button><button className="primary-btn">Save Expense</button></div></form></Modal>}
 </Layout>
}
function Table({headers,rows}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((cell,j)=><td key={j}>{cell}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty">No records found.</td></tr>}</tbody></table></div>}
